name: NodeJS with Gulp

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true

      - uses: salsify/action-detect-and-tag-new-version@v2
        id: tagauto
        with:
          create-tag: true

      - name: list tag output
        run: |
          echo "previous-version ${{ steps.tagauto.outputs.previous-version }}"
          echo "current-version ${{ steps.tagauto.outputs.current-version }}"
          echo "tagautotag ${{ steps.tagauto.outputs.tag }}"

      # - name: Replace values in package JSON
      #   uses: tnikFi/json-file-transform@v1
      #   if: steps.autotag.outputs.old_tag != ''
      #   with:
      #     files: "**/package.json"
      #     key-value-pairs: |
      #       version=${{ steps.autotag.outputs.tag }}

      - name: Build
        run: |
          npm install
          gulp bundle --ship
          gulp package-solution --ship

      - name: Artifact
        uses: actions/upload-artifact@v4
        if: steps.tagauto.outputs.previous-version != steps.tagauto.outputs.current-version && steps.tagauto.outputs.current-version != ''
        with:
          name: spfx-solution
          path: ./dist/deploy/sp-fx-extensions.sppkg

      - name: Release
        uses: softprops/action-gh-release@v2
        if: steps.tagauto.outputs.previous-version != steps.tagauto.outputs.current-version && steps.tagauto.outputs.current-version != ''
        with:
          make_latest: true
          tag_name: ${{ steps.tagauto.outputs.tag }}
          files: |
            ./dist/deploy/sp-fx-extensions.sppkg
      - name: Release To NPM
        if: steps.tagauto.outputs.previous-version != steps.tagauto.outputs.current-version && steps.tagauto.outputs.current-version != ''
        run: |
          npm publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
